name: Run Python Script

on:
  schedule:
    - cron: '0 1 * * *' # 0 22 L * *

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.1"] # Replace with the version of Python you want to use
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f itinerario/requirements.txt ]; then pip install -r itinerario/requirements.txt; fi
      - name: Run script
        run: python itinerario/itinerario_data_getter.py # Replace with the path to your Python script
